services:

  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db: