services:

  app:
    container_name: app
    build:
      context: .
    ports:
      - 9000:9000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_test
    networks:
      - spring
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    networks:
      - spring
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  spring:
    name: spring
    driver: bridge

volumes:
  db: