services:

  app:
    container_name: app-jpa
    build:
      context: .
    environment:
      - DB_HOST=postgres-db
    ports:
      - 9000:9000
    networks:
      - spring
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - spring
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  spring:
    name: spring
    driver: bridge

volumes:
  db:
